export const tableSchema = {
  InlineForm: {
    head: [
      { name: "SHIFT" },
      { name: "AV" },
      { name: "Platform" },
      { name: "Date" },
      { name: "Outbound" },
      { name: "Inbound" },
      { name: "Overnight" },
      { name: "FIRST" },
      { name: "BAR" },
      { name: "PURSER" },
      { name: "FOR:", className: "FOR" },
      { name: "Early", className: "FOR" },
      { name: "Late", className: "FOR" },
      { name: "LTA", className: "FOR" },
      { name: "DO", className: "FOR" },
      { name: "Note", className: "FOR" },
    ],
  },
  SwapDisplay: {
    head: [
      { name: "Date" },
      { name: "Outbound" },
      { name: "Inbound" },
      { name: "Position" },
      { name: "Email" },
      { name: "FOR:", className: "FOR" },
      { name: "Early", className: "FOR" },
      { name: "Late", className: "FOR" },
      { name: "LTA", className: "FOR" },
      { name: "DO", className: "FOR" },
      { name: "Note", className: "FOR" },
      { name: "Sent" },
    ],
  },
};
